replicaCount: 1

image:
  repository: edcelvista/golang-api
  tag: "0.0.3"
  pullPolicy: IfNotPresent

# service:
#   type: ClusterIP
#   port: 80

env: # []
  - name: SSL_CERT
    value: "/tls/tls.crt"
  - name: SSL_KEY
    value: "/tls/tls.key"

resources: 
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 512Mi